fail_on_severity: "low"
allow_licenses:
  - "MIT"
  - "MIT-0"
  - "ISC"
  - "MPL-2.0"
  - "BSD-2-Clause"
  - "BSD-3-Clause"
  - "Apache-2.0"
  - "LicenseRef-scancode-google-patent-license-golang"
allow-dependencies-licenses:
  # Have a separate non-GPL license.
  - "pkg:golang/github.com/grafana/loki/pkg/push"
  # Used in CI, is not directly linked or used by oteldb.
  - "pkg:actions/go-task/setup-task"
