apiVersion: 1

datasources:
  - name: "TraceQL"
    type: tempo
    access: proxy
    orgId: 1
    url: http://oteldb:3200
    uid: tempo-oteldb
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        # Field with an internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the uid value of the logs data source.
        datasourceUid: "loki-oteldb"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        customQuery: true
        query: '{$${__tags}} |= "$${__span.traceId}"'
        tags:
          - key: service.name
            value: service_name
      tracesToMetrics:
        datasourceUid: "prom-oteldb"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags:
          - key: service.name
            value: service_name
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prom-oteldb
      lokiSearch:
        datasourceUid: "loki-oteldb"
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Bearer oteldb-secret-token"

  - name: "LogQL"
    type: loki
    access: proxy
    orgId: 1
    url: http://oteldb:3100
    uid: loki-oteldb
    jsonData:
      serviceMap:
        datasourceUid: prom-oteldb
      maxLines: 500
      derivedFields:
        - datasourceUid: tempo-oteldb
          matcherType: label
          matcherRegex: trace_id
          name: trace
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin

  - name: "PromQL"
    type: prometheus
    access: proxy
    orgId: 1
    isDefault: true
    url: http://oteldb:9090
    uid: prom-oteldb

    jsonData:
      prometheusType: Prometheus
      disableRecordingRules: false
      exemplarTraceIdDestinations:
        - datasourceUid: tempo-oteldb
          name: trace_id
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Bearer prometheus-very-secret-token"

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      port: 9000
      server: clickhouse
      tlsSkipVerify: true
